pragma Singleton
import QtQuick

QtObject {
    id: i18n

    // Bahasa aktif saat ini. Default: "en" (English)
    property string currentLanguage: "en"

    readonly property bool isEnglish: currentLanguage === "en"
    readonly property bool isIndonesian: currentLanguage === "id"

    // Daftar bahasa yang didukung
    readonly property var availableLanguages: [
        { code: "en", name: "English", flag: "🇺🇸" },
        { code: "id", name: "Bahasa Indonesia", flag: "🇮🇩" }
    ]

    // Kamus terpusat teks multi-bahasa (Otomatis disinkronkan oleh scripts/sync_i18n.py)
    readonly property var strings: ({
        "en": {
            "A connection problem occurred": "A connection problem occurred",
            "Active": "Active",
            "Activity Monitor": "Activity Monitor",
            "Activity temporarily paused": "Activity temporarily paused",
            "activityMonitor": "Activity Monitor",
            "Add": "Add",
            "Add Application": "Add Application",
            "Add Productivity Application": "Add Productivity Application",
            "Add task details (Optional)": "Add task details (Optional)",
            "Adjust your profile picture": "Adjust your profile picture",
            "An Error Occurred": "An Error Occurred",
            "application": "Application",
            "Application": "Application",
            "Application List:": "Application List:",
            "Application Name:": "Application Name:",
            "Application Requests": "Application Requests",
            "Application Usage": "Application Usage",
            "Apply": "Apply",
            "authError": "Authentication Session Expired",
            "authErrorDesc": "Your session has expired. Please sign in again.",
            "Back to Login Page": "Back to Login Page",
            "cancel": "Cancel",
            "Cancel": "Cancel",
            "Check Update": "Check Update",
            "Check Update now": "Check Update now",
            "checkUpdate": "Check Update",
            "Choose a profile picture": "Choose a profile picture",
            "Clear": "Clear",
            "clockIn": "Clock In",
            "clockOut": "Clock Out",
            "Close": "Close",
            "confirm": "Confirm",
            "confirmSwitch": "Switch to Project?",
            "confirmSwitchDesc": "You have an active task. Do you want to switch to this task?",
            "Connection Error": "Connection Error",
            "connectionError": "Connection Error",
            "Crop Profile Picture": "Crop Profile Picture",
            "Current Window": "Current Window",
            "currentTask": "Current Task",
            "currentWindow": "Current Window",
            "Dark Mode": "Dark Mode",
            "darkMode": "Dark Mode",
            "delete": "Delete",
            "deskmon": "Deskmon",
            "Deskmon Website": "Deskmon Website",
            "dismiss": "Dismiss",
            "Dismiss": "Dismiss",
            "Duration": "Duration",
            "Early Clock Out": "Early Clock Out",
            "Email": "Email",
            "emptyCredentials": "Username and password cannot be empty",
            "english": "English",
            "Enter application name, make sure the name is correct": "Enter application name, make sure the name is correct",
            "Enter website domain (example: youtube.com, google.com, etc)": "Enter website domain (example: youtube.com, google.com, etc)",
            "Enter your password": "Enter your password",
            "Enter your username": "Enter your username",
            "Example: Finished fixing bugs on a feature...": "Example: Finished fixing bugs on a feature...",
            "Example: Need verification from project manager, technical issues, etc.": "Example: Need verification from project manager, technical issues, etc.",
            "Failed to send data to server.": "Failed to send data to server.",
            "filterDate": "Filter Date",
            "finishTask": "Finish Task",
            "For": "For",
            "Idle": "Idle",
            "Idle Detected": "Idle Detected",
            "idleDetected": "Idle Detected",
            "idleMessage": "No mouse or keyboard activity detected for a while.",
            "indonesian": "Bahasa Indonesia",
            "language": "Language",
            "Language": "Language",
            "Last Month": "Last Month",
            "Last Week": "Last Week",
            "Later": "Later",
            "Light Mode": "Light Mode",
            "lightMode": "Light Mode",
            "loginAgain": "Sign In Again",
            "loginFailed": "Login failed",
            "logout": "Logout",
            "Logout": "Logout",
            "Mark as Need Review": "Mark as Need Review",
            "mode": "Appearance Mode",
            "Monitored Applications": "Monitored Applications",
            "monitoredApps": "Monitored Apps",
            "Move and zoom the image to fit the circular frame": "Move and zoom the image to fit the circular frame",
            "My Profile": "My Profile",
            "needReview": "Mark as Need Review",
            "neutral": "Neutral",
            "Neutral": "Neutral",
            "No active task": "No active task",
            "noActiveTask": "No Active Task",
            "Non-Productive": "Non-Productive",
            "Non-Productive Apps": "Non-Productive Apps",
            "nonProductive": "Non-Productive",
            "Not specified": "Not specified",
            "OK": "OK",
            "password": "Password",
            "Password": "Password",
            "passwordPlaceholder": "Enter your password",
            "Pause": "Pause",
            "Paused": "Paused",
            "pauseTask": "Pause Task",
            "Pending Application Requests": "Pending Application Requests",
            "Please enter your reason here": "Please enter your reason here",
            "Please provide your reason": "Please provide your reason",
            "Please sign in again": "Please sign in again",
            "productive": "Productive",
            "Productive": "Productive",
            "Productive Apps": "Productive Apps",
            "Productivity": "Productivity",
            "Productivity Type": "Productivity Type",
            "productivityStatistics": "Productivity Statistics",
            "profile": "My Profile",
            "Profile": "Profile",
            "Provide a clear reason for review": "Provide a clear reason for review",
            "Quick Select": "Quick Select",
            "Reason": "Reason",
            "Recent Activity": "Recent Activity",
            "Recorded clock-in at: ": "Recorded clock-in at: ",
            "recordedClockIn": "Recorded entry time: ",
            "refresh": "Refresh",
            "Refresh": "Refresh",
            "Request": "Request",
            "resume": "Resume",
            "Resume": "Resume",
            "resumeTask": "Resume Task",
            "retry": "Retry",
            "Retry": "Retry",
            "Review": "Review",
            "Review Request": "Review Request",
            "Review Request Reason": "Review Request Reason",
            "Role": "Role",
            "Role not set": "Role not set",
            "save": "Save",
            "Save": "Save",
            "Search applications...": "Search applications...",
            "seeAll": "See All",
            "seeLess": "See Less",
            "Select Date Range": "Select Date Range",
            "selectDateRange": "Select Date Range",
            "Selected file is invalid or cannot be accessed": "Selected file is invalid or cannot be accessed",
            "Sending data...": "Sending data...",
            "Sending...": "Sending...",
            "Session Expired": "Session Expired",
            "settings": "Settings",
            "Settings": "Settings",
            "Show Applications": "Show Applications",
            "Sign In": "Sign In",
            "Sign in to track your activity": "Sign in to track your activity",
            "signIn": "Sign In",
            "signingIn": "Signing in...",
            "signInSubtitle": "Sign in to continue monitoring your tasks",
            "Skip": "Skip",
            "Submit": "Submit",
            "Switch Project": "Switch Project",
            "Switch to Dark Mode": "Switch to Dark Mode",
            "Switch to Light Mode": "Switch to Light Mode",
            "Switch to Project?": "Switch to Project?",
            "switchProject": "Switch Project",
            "switchToDarkMode": "Switch to Dark Mode",
            "switchToLightMode": "Switch to Light Mode",
            "target": "Target",
            "Target": "Target",
            "Task Details": "Task Details",
            "Task Time Warning": "Task Time Warning",
            "taskDetails": "Task Details",
            "The task will be moved to ": "The task will be moved to ",
            "This is a status message": "This is a status message",
            "This Month": "This Month",
            "This Week": "This Week",
            "Time": "Time",
            "Time At Work": "Time At Work",
            "timeAtWork": "Time At Work",
            "timeUp": "Time is Up",
            "timeUpFinished": "Your task time has expired.",
            "timeUpWarning": "Your task time has less than 10 minutes remaining!",
            "Title": "Title",
            "today": "Today",
            "Today": "Today",
            "topApps": "Top Applications",
            "topDomains": "Top Websites",
            "Total Logs": "Total Logs",
            "Unknown": "Unknown",
            "Update Available": "Update Available",
            "Update Now": "Update Now",
            "URL": "URL",
            "username": "Username",
            "Username": "Username",
            "Username not set": "Username not set",
            "usernamePlaceholder": "Enter your username or email",
            "Version": "Version",
            "View All": "View All",
            "Waiting for clock-in data...": "Waiting for clock-in data...",
            "waitingClockIn": "Waiting for clock-in data...",
            "Warning": "Warning",
            "Website Domain:": "Website Domain:",
            "Website Usage": "Website Usage",
            "welcomeBack": "Welcome Back",
            "Window Title": "Window Title",
            "windowTitle": "Title",
            "Yesterday": "Yesterday",
            "You can add details of what you worked on in the previous task here (Optional)": "You can add details of what you worked on in the previous task here (Optional)",
            "You have an active task. Do you want to switch to this task?": "You have an active task. Do you want to switch to this task?",
            "Zoom": "Zoom"
        },
        "id": {
            "A connection problem occurred": "Terjadi masalah koneksi",
            "Active": "Aktif",
            "Activity Monitor": "Pemantau Aktivitas",
            "Activity temporarily paused": "Aktivitas dihentikan sementara",
            "activityMonitor": "Pemantau Aktivitas",
            "Add": "Tambah",
            "Add Application": "Tambah Aplikasi",
            "Add Productivity Application": "Tambah Aplikasi Produktivitas",
            "Add task details (Optional)": "Tambahkan detail tugas (Opsional)",
            "Adjust your profile picture": "Sesuaikan gambar profil Anda",
            "An Error Occurred": "Terjadi Kesalahan",
            "application": "Aplikasi",
            "Application": "Aplikasi",
            "Application List:": "Daftar Aplikasi:",
            "Application Name:": "Nama Aplikasi:",
            "Application Requests": "Permintaan Aplikasi",
            "Application Usage": "Penggunaan Aplikasi",
            "Apply": "Terapkan",
            "authError": "Sesi Autentikasi Berakhir",
            "authErrorDesc": "Sesi Anda telah kedaluwarsa. Silakan masuk kembali.",
            "Back to Login Page": "Kembali ke Halaman Masuk",
            "cancel": "Batal",
            "Cancel": "Batal",
            "Check Update": "Periksa Pembaruan",
            "Check Update now": "Periksa Perbarui sekarang",
            "checkUpdate": "Cek Pembaruan",
            "Choose a profile picture": "Pilih gambar profil",
            "Clear": "Reset",
            "clockIn": "Jam Masuk",
            "clockOut": "Jam Keluar",
            "Close": "Tutup",
            "confirm": "Konfirmasi",
            "confirmSwitch": "Beralih ke Proyek?",
            "confirmSwitchDesc": "Ada pekerjaan yang sedang berjalan. Apakah Anda yakin ingin beralih?",
            "Connection Error": "Kesalahan Koneksi",
            "connectionError": "Gangguan Koneksi",
            "Crop Profile Picture": "Pangkas Gambar Profil",
            "Current Window": "Jendela Saat Ini",
            "currentTask": "Pekerjaan Saat Ini",
            "currentWindow": "Jendela Saat Ini",
            "Dark Mode": "Mode Gelap",
            "darkMode": "Mode Gelap",
            "delete": "Hapus",
            "deskmon": "Deskmon",
            "Deskmon Website": "Situs Web Deskmon",
            "dismiss": "Abaikan",
            "Dismiss": "Abaikan",
            "Duration": "Durasi",
            "Early Clock Out": "Jam Keluar Lebih Awal",
            "Email": "E-mail",
            "emptyCredentials": "Username dan password tidak boleh kosong",
            "english": "English",
            "Enter application name, make sure the name is correct": "Masukkan nama aplikasi, pastikan nama sudah benar",
            "Enter website domain (example: youtube.com, google.com, etc)": "Masukkan domain situs web (contoh: youtube.com, google.com, dll)",
            "Enter your password": "Masukkan kata sandi Anda",
            "Enter your username": "Masukkan nama pengguna Anda",
            "Example: Finished fixing bugs on a feature...": "Contoh: Selesai memperbaiki bug pada suatu fitur...",
            "Example: Need verification from project manager, technical issues, etc.": "Contoh: Perlu verifikasi dari manajer proyek, masalah teknis, dll.",
            "Failed to send data to server.": "Gagal mengirim data ke server.",
            "filterDate": "Pilih Tanggal",
            "finishTask": "Selesaikan Pekerjaan",
            "For": "Untuk",
            "Idle": "Tidak Aktif",
            "Idle Detected": "Tidak Aktif Terdeteksi",
            "idleDetected": "Tidak Aktif Terdeteksi",
            "idleMessage": "Tidak ada aktivitas mouse atau keyboard dalam beberapa waktu.",
            "indonesian": "Bahasa Indonesia",
            "language": "Bahasa",
            "Language": "Bahasa",
            "Last Month": "Bulan Lalu",
            "Last Week": "Minggu lalu",
            "Later": "Nanti",
            "Light Mode": "Mode Terang",
            "lightMode": "Mode Terang",
            "loginAgain": "Masuk Kembali",
            "loginFailed": "Gagal masuk",
            "logout": "Keluar",
            "Logout": "Keluar",
            "Mark as Need Review": "Tandai sebagai Perlu Tinjauan",
            "mode": "Mode Tampilan",
            "Monitored Applications": "Aplikasi yang Dipantau",
            "monitoredApps": "Aplikasi Terpantau",
            "Move and zoom the image to fit the circular frame": "Pindahkan dan perbesar gambar agar sesuai dengan bingkai melingkar",
            "My Profile": "Profil Saya",
            "needReview": "Tandai Perlu Review",
            "neutral": "Netral",
            "Neutral": "Netral",
            "No active task": "Tidak ada tugas aktif",
            "noActiveTask": "Tidak Ada Pekerjaan Aktif",
            "Non-Productive": "Non-Produktif",
            "Non-Productive Apps": "Aplikasi Non-Produktif",
            "nonProductive": "Non-Produktif",
            "Not specified": "Tidak ditentukan",
            "OK": "OKE",
            "password": "Kata Sandi",
            "Password": "Kata Sandi",
            "passwordPlaceholder": "Masukkan kata sandi",
            "Pause": "Jeda",
            "Paused": "Dijeda",
            "pauseTask": "Jeda Pekerjaan",
            "Pending Application Requests": "Permintaan Aplikasi yang Tertunda",
            "Please enter your reason here": "Silakan masukkan alasan Anda di sini",
            "Please provide your reason": "Silakan berikan alasan Anda",
            "Please sign in again": "Silakan masuk lagi",
            "productive": "Produktif",
            "Productive": "Produktif",
            "Productive Apps": "Aplikasi Produktif",
            "Productivity": "Produktivitas",
            "Productivity Type": "Jenis Produktivitas",
            "productivityStatistics": "Statistik Produktivitas",
            "profile": "Profil Saya",
            "Profile": "Profil",
            "Provide a clear reason for review": "Berikan alasan yang jelas untuk peninjauan",
            "Quick Select": "Pilih Cepat",
            "Reason": "Alasan",
            "Recent Activity": "Aktivitas Terkini",
            "Recorded clock-in at: ": "Jam masuk yang tercatat pada:",
            "recordedClockIn": "Tercatat masuk pada jam: ",
            "refresh": "Segarkan",
            "Refresh": "Segarkan",
            "Request": "Ajukan",
            "resume": "Lanjutkan",
            "Resume": "Lanjutkan",
            "resumeTask": "Lanjutkan Pekerjaan",
            "retry": "Coba Lagi",
            "Retry": "Coba Lagi",
            "Review": "Tinjauan",
            "Review Request": "Permintaan Tinjauan",
            "Review Request Reason": "Alasan Permintaan Tinjauan",
            "Role": "Peran",
            "Role not set": "Peran belum ditetapkan",
            "save": "Simpan",
            "Save": "Simpan",
            "Search applications...": "Cari aplikasi...",
            "seeAll": "Lihat Semua",
            "seeLess": "Lebih Sedikit",
            "Select Date Range": "Pilih Rentang Tanggal",
            "selectDateRange": "Rentang Tanggal",
            "Selected file is invalid or cannot be accessed": "File yang dipilih tidak valid atau tidak dapat diakses",
            "Sending data...": "Mengirim data...",
            "Sending...": "Mengirim...",
            "Session Expired": "Sesi Berakhir",
            "settings": "Pengaturan",
            "Settings": "Pengaturan",
            "Show Applications": "Tampilkan Aplikasi",
            "Sign In": "Masuk",
            "Sign in to track your activity": "Masuk untuk melacak aktivitas Anda",
            "signIn": "Masuk",
            "signingIn": "Sedang masuk...",
            "signInSubtitle": "Masuk untuk melanjutkan pemantauan pekerjaan Anda",
            "Skip": "Lewati",
            "Submit": "Kirim",
            "Switch Project": "Ganti Proyek",
            "Switch to Dark Mode": "Beralih ke Mode Gelap",
            "Switch to Light Mode": "Beralih ke Mode Terang",
            "Switch to Project?": "Beralih ke Proyek?",
            "switchProject": "Beralih Proyek",
            "switchToDarkMode": "Beralih ke Mode Gelap",
            "switchToLightMode": "Beralih ke Mode Terang",
            "target": "Target",
            "Target": "Target",
            "Task Details": "Detail Tugas",
            "Task Time Warning": "Peringatan Waktu Tugas",
            "taskDetails": "Detail Pekerjaan",
            "The task will be moved to ": "Tugas akan dipindahkan ke",
            "This is a status message": "Ini adalah pesan status",
            "This Month": "Bulan ini",
            "This Week": "Minggu ini",
            "Time": "Waktu",
            "Time At Work": "Waktu Di Tempat Kerja",
            "timeAtWork": "Waktu Kerja",
            "timeUp": "Waktu Habis",
            "timeUpFinished": "Waktu pekerjaan Anda sudah habis.",
            "timeUpWarning": "Waktu pekerjaan Anda tersisa kurang dari 10 menit!",
            "Title": "Judul",
            "today": "Hari Ini",
            "Today": "Hari ini",
            "topApps": "Aplikasi Teratas",
            "topDomains": "Situs Teratas",
            "Total Logs": "Jumlah Log",
            "Unknown": "Tidak dikenal",
            "Update Available": "Pembaruan Tersedia",
            "Update Now": "Perbarui Sekarang",
            "URL": "URL",
            "username": "Nama Pengguna",
            "Username": "Nama Pengguna",
            "Username not set": "Nama pengguna belum disetel",
            "usernamePlaceholder": "Masukkan username atau email",
            "Version": "Versi",
            "View All": "Lihat Semua",
            "Waiting for clock-in data...": "Menunggu data jam masuk...",
            "waitingClockIn": "Menunggu data jam masuk...",
            "Warning": "Peringatan",
            "Website Domain:": "Domain Situs Web:",
            "Website Usage": "Penggunaan Situs Web",
            "welcomeBack": "Selamat Datang Kembali",
            "Window Title": "Judul Jendela",
            "windowTitle": "Judul",
            "Yesterday": "Kemarin",
            "You can add details of what you worked on in the previous task here (Optional)": "Anda dapat menambahkan detail tentang apa yang Anda kerjakan pada tugas sebelumnya di sini (Opsional)",
            "You have an active task. Do you want to switch to this task?": "Anda memiliki tugas aktif. Apakah Anda ingin beralih ke tugas ini?",
            "Zoom": "Perbesar"
        }
    })

    /**
     * Fungsi penerjemah: I18n.t("key", "Default Fallback")
     */
    function t(key, fallback) {
        var langDict = strings[currentLanguage];
        if (langDict && langDict[key] !== undefined) {
            return langDict[key];
        }
        var enDict = strings["en"];
        if (enDict && enDict[key] !== undefined) {
            return enDict[key];
        }
        return fallback !== undefined ? fallback : key;
    }

    /**
     * Alias singkat agar mudah diketik: Lang.tr("Logout")
     */
    function tr(key, fallback) {
        return t(key, fallback);
    }

    /**
     * Mengubah bahasa aktif ("en" atau "id")
     */
    function setLanguage(code) {
        if (strings[code]) {
            currentLanguage = code;
        }
    }
}
